### PR TITLE
support for ALAssetsGroupPhotoStream

### PR DESCRIPTION
**Pull request by lxzhh**
add support for ALAssetsGroupPhotoStream in iOS8

### CODE REVIEW

**Comment by pavelosipov** [comment]
Thank you for fixing stream for photos from shared photo stream! I'll made by my self minor refactoring to remove logging and copy-paste.

**Comment by pavelosipov** [comment]
I detected strange crash in master with photos from shared photo stream, so I didn't update library in cocoapods repository. I'll do my best to fix it asap.

**Comment by pavelosipov** [comment]
I fixed crash. Your pull request is refactored and published in pod v2.2.0.

**Comment by lxzhh** [comment]
That will be great.

**Comment by pavelosipov** [comment]
Now stream supports even adjusted photos from photostream, applying filters on the fly.

**Comment by pavelosipov** [comment]
I removed applying filters for photos from shared photostream on iOS 8, because some of them can not be found via Photos.framework. Now it works exactly as in your pull request. Enjoy pod with version 2.2.1.

**Pull request merged**
